version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: mediaapp
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: mediaapp
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - towerview-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mediaapp"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  app:
    build:
      context: .
      dockerfile: Dockerfile.combined
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://mediaapp:${DB_PASSWORD}@db:5432/mediaapp
      REDIS_URL: redis://localhost:6379
      SECRET_KEY: ${SECRET_KEY}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      # Production settings
      PYTHONUNBUFFERED: 1
      TZ: ${TZ:-UTC}
    ports:
      - "${HTTP_PORT:-80}:80"        # Web interface
      # Remove direct backend port in production for security
    volumes:
      # Optional: Mount for persistent redis data
      - redis-data:/data
      # Optional: Mount for logs
      - ./logs:/var/log
    networks:
      - towerview-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

networks:
  towerview-network:
    driver: bridge

volumes:
  db-data:
  redis-data: