version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: mediaapp
      POSTGRES_PASSWORD: ${DB_PASSWORD:-change_me}
      POSTGRES_DB: mediaapp
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mediaapp"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.combined
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://mediaapp:${DB_PASSWORD:-change_me}@db:5432/mediaapp
      REDIS_URL: redis://localhost:6379
      SECRET_KEY: ${SECRET_KEY:-your-secret-key-change-me}
      ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin}
    ports:
      - "8080:80"      # Nginx serving frontend and proxying to backend
      - "8001:8000"    # Direct backend access (optional, can be removed)
    restart: unless-stopped

volumes:
  db-data: